//
// Created by arnau on 09/06/2022.
//

#ifndef THESHOOTER_VALUES_H
#define THESHOOTER_VALUES_H

#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <time.h>

//EXT
#define EXT_SUPERBLOCK_OFFSET 1024
#define EXT_SUPERBLOCK_SIZE 1024
#define EXT_MAGIC_OFFSET 56
#define EXT_MAGIC 0xEF53
#define EXT_ROOT_INODE 2
#define EXT_NUM_DIR_ENTRIES 512
#define EXT_FILE_NAME_LEN 255
#define EXT_DIR_FILETYPE 2
#define EXT_NUM_BLOCKS 12

#define EXT_INO_SIZE_OFFSET 88
#define EXT_INO_SIZE_SIZE 2
#define EXT_INO_NUMINODES_OFFSET 0
#define EXT_INO_NUMINODES_SIZE 4
#define EXT_INO_FIRSTINODE_OFFSET 84
#define EXT_INO_FIRSTINODE_SIZE 4
#define EXT_INO_INODESGROUP_OFFSET 40
#define EXT_INO_INODESGROUP_SIZE 4
#define EXT_INO_FREEINODES_OFFSET 16
#define EXT_INO_FREEINODES_SIZE 4

#define EXT_BLO_SIZE_OFFSET 24
#define EXT_BLO_SIZE_SIZE 4
#define EXT_BLO_RSVBLOCKS_OFFSET 8
#define EXT_BLO_RSVBLOCKS_SIZE 4
#define EXT_BLO_FREEBLOCKS_OFFSET 12
#define EXT_BLO_FREEBLOCKS_SIZE 4
#define EXT_BLO_TOTALBLOCKS_OFFSET 4
#define EXT_BLO_TOTALBLOCKS_SIZE 4
#define EXT_BLO_FIRSTBLOCK_OFFSET 20
#define EXT_BLO_FIRSTBLOCK_SIZE 4
#define EXT_BLO_GROUPBLOCKS_OFFSET 32
#define EXT_BLO_GROUPBLOCKS_SIZE 4

#define EXT_VOL_NAME_OFFSET 120
#define EXT_VOL_NAME_SIZE 16
#define EXT_VOL_LASTCHECK_OFFSET 64
#define EXT_VOL_LASTCHECK_SIZE 4
#define EXT_VOL_LASTMOUNT_OFFSET 44
#define EXT_VOL_LASTMOUNT_SIZE 4
#define EXT_VOL_LASTWRITE_OFFSET 48
#define EXT_VOL_LASTWRITE_SIZE 4

#define EXT_GDT_INODETABLE_OFFSET 8
#define EXT_GDT_INODETABLE_SIZE 4

//FAT
#define FAT_NAME_OFFSET 3
#define FAT_NAME_SIZE 8
#define FAT_SIZE_OFFSET 11
#define FAT_SIZE_SIZE 2
#define FAT_SECTORSCLUSTER_OFFSET 13
#define FAT_SECTORSCLUSTER_SIZE 1
#define FAT_RESERVEDSECTORS_OFFSET 14
#define FAT_RESERVEDSECTORS_SIZE 2
#define FAT_NUMFATS_OFFSET 16
#define FAT_NUMFATS_SIZE 1
#define FAT_MAXROOTENTRIES_OFFSET 17
#define FAT_MAXROOTENTRIES_SIZE 2
#define FAT_SECTORSFAT_OFFSET 22
#define FAT_SECTORSFAT_SIZE 2
#define FAT_LABEL_OFFSET 43
#define FAT_LABEL_SIZE 11

#define FAT_DIR_ENTRY_SIZE 32
#define FAT_FILENAME_SIZE 11
#define FAT_DIR_ENTRY_CLUSTER_OFFSET 26
#define FAT_DIR_ENTRY_CLUSTER_SIZE 2
#define FAT_DIR_ENTRY_SIZE_OFFSET 28
#define FAT_DIR_ENTRY_SIZE_SIZE 4
#define FAT_DIR_ENTRY_ATTR_OFFSET 11

#endif //THESHOOTER_VALUES_H
